#!/bin/sh
#
# Super Simple Static Site Generator
#
# This script will abuse pandoc to create
# a fabulous bare-bones static site.

main() {
    # Some housekeeping that's probably not 100% necessary
    rm -rf dst tmp && mkdir -p src/css src/posts \
        dst/posts dst/tags tmp/tags tmp/posts
    find src -type d | sed 's/src/dst/' | xargs mkdir -p
    # We expect the following files to exist. If they're not there, make blank ones.
    touch src/config.yaml src/_top.html src/_bottom.html src/_header.html \
        src/index.md src/posts.md src/tags
    cp src/*md tmp/
    cp src/*html dst/
    cp src/*txt dst/

    # Generate tmp/posts/*.md, tmp/index.md, tmp/posts.md, tmp/tags.md,
    # tmp/tags/example-tag.md files, using our posts as a source
    find src/posts -type f -name "*.md" | sort -r | generate_tmp_posts_files

    # Generate tags.md file. Grab the list of tags from our tmp/tags directory,
    # then chuck them all into a tmp directory, which we then sort & pandoc-ise.
    tags=$(find tmp/tags -type f -print0 | xargs -0 -I {} basename {} ".md")
    echo "$tags" | while read -r tag; do
        tag_count="$(wc -l < tmp/tags/"$tag".md | xargs)"
        echo "$tag_count-=-- [$tag](tags/$tag.html) ($tag_count)" >> tmp/tags-unsorted.md
        tags_file=$(cat "tmp/tags/$tag.md")
        printf -- "---\ntitle: %s tags\n---\n\n%s" "$tag" "$tags_file" > "tmp/tags/$tag.md"
    done
    sort -rn tmp/tags-unsorted.md | awk -F'-=-' '{ print $2 }'  >> tmp/tags.md
    rm tmp/tags-unsorted.md

    # Find all markdown files in out tmp directory and then turn them into
    # corresponding html in the dst path.
    find src tmp -name "*.md" -type f ! -path 'src/posts/*' | while read -r file; do
        html_dst_path="$(echo "$file" |  sed -e 's/src/dst/;s/tmp/dst/;s/\.md$/\.html/')"
        md_file_to_html_file "$file" > "$html_dst_path"
    done

    generate_rss_feed > dst/index.xml

    cp -R src/css/. dst/css/.

    # create a super-simple sitemap of all html files.
    for file in dst/**/*.html; do
        add_to_sitemap "$file"
    done

    echo "Generated $(find dst | wc -l) files"
}

md_file_to_html_file() {
    input_file="$1"
    description=$(grep -iE '^description: ' "$1" | cut -d' ' -f 2-)
    pandoc \
        --css="/css/style.css" \
        --highlight-style zenburn \
        --include-in-header src/_header.html \
        --include-before-body src/_top.html \
        --include-after-body src/_bottom.html \
        --title "$(config_for title)" \
        --metadata "header-includes: <meta name=\"description\" content=\"$description\" />" \
        --to=html5  \
        "$input_file"
}

# Generate tmp/posts/*.md, tmp/index.md, tmp/posts.md, tmp/tags.md,
# tmp/tags/example-tag.md files, using our posts as a source
generate_tmp_posts_files() {
    # For every post, we want to:
    while read -r post_file_path; do
        # Assigning variables from the front-matter of the markdown post
        post_md_file=$(cat "$post_file_path")
        title=$(grep -iE '^title: ' "$post_file_path"| cut -d' ' -f 2-)
        description=$(grep -iE '^description: ' "$post_file_path" | cut -d' ' -f 2-)
        post_date=$(grep -iE '^date: ' "$post_file_path" | cut -d' ' -f 2-)
        tags=$(grep -iE '^tags: ' "$post_file_path" | cut -d' ' -f 2-)
        split_tags=$(echo "$tags" | sed -E 's/\s+$//' | tr ' ' '\n')

        # Calculate the ultimate root paths for the generated html files
        dst_path=$(echo "$post_file_path" | sed -e's#src/##' -e's/\.md$/\.html/' -e's#tags/##')

        # A list of tags converted to a list of markdown links
        linked_tags=$(echo "$split_tags" | xargs -I {} echo "[{}](/tags/{}.html)")

        # Add a heading from every post into the index.md / posts.md
        # and generate all our tags
        printf "## [%s](%s)\n%s\n%s\n\n" "$title" "$dst_path" "$description" "$linked_tags" >> tmp/index.md
        printf -- "- *%s* [%s](%s)\n\n" "$post_date" "$title" "$dst_path" >> tmp/posts.md
        echo "$split_tags" | xargs -I "{tag}" sh -c "echo \"- *[$title](/$dst_path)* $post_date\" >> tmp/tags/{tag}.md"
        if [ -n "$linked_tags" ]; then
            tmp_path="$(echo "$post_file_path" | sed 's#src/#tmp/#')"
            cat "$post_file_path" > "$tmp_path"
            printf "\n\n---\n\n## Tags\n\n%s" "$linked_tags" >> "$tmp_path"
        fi
        # Add an RSS element for the page
        post_html_fragment="$(echo "$post_md_file" | tail -n +7 | pandoc --from markdown --to=html5)"
        echo "<item>
<title>$(echo "$title" | xml_encode)</title>
<link>$(config_for base_url)/$(echo "$dst_path" | xml_encode)</link>
<pubDate>$(date_func -d "$post_date" -R)</pubDate>
<guid>$(config_for base_url)/$(echo "$dst_path" | xml_encode)</guid>
<description><![CDATA[$post_html_fragment]]></description>
</item>" >> tmp/index.xml
    done
}

xml_encode() {
    sed "s/\&/\&amp;/g;s/>/\&gt;/g;s/</\&lt;/g;s/'/\&apos;/g"
}

config_for() {
    grep "^$1: " src/config.yaml | cut -d' ' -f2-
}

generate_rss_feed() {
    echo "<rss xmlns:atom=\"http://www.w3.org/2005/Atom\" version=\"2.0\">
<channel>
<title>$(config_for rss_title)</title>
<link>$(config_for base_url)</link>
<description>$(config_for rss_description)</description>
<generator>ssssg</generator>
<lastBuildDate>$(date_func -R)</lastBuildDate>
<atom:link href=\"$(config_for base_url)/index.xml\" rel=\"self\" type=\"application/rss+xml\"/>"
    cat tmp/index.xml
    echo "</channel></rss>"
}

add_to_sitemap() {
    echo "$1" | sed -e "s;dst;$(config_for base_url);" >> dst/sitemap.txt
}

date_func() {
    if [ "$(uname)" = "Darwin" ]; then
        gdate || echo "Please 'brew install coreutils'" && exit 1
    else
        date
    fi
}

if [ $# -gt 0 ]; then
    echo "Usage: ssssg"
    echo "  No need to pass any arguments in."
    echo "  Read the README.md from  https://git.sr.ht/~will-clarke/super-simple-static-site-generator for more information."
    exit 1
fi

main
